version: '3.8'

services:
  laravel:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:prvrkVu4bDvOnk7fIcWfKMCgzXI0jAyu5i99osjVpDw=
      DB_CONNECTION: mysql
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_DATABASE: school_management_laravel
      DB_USERNAME: root
      DB_PASSWORD: 25021999
