services:
  laravel:
    # Isso monta o código do projeto no container
    volumes:
      - .:/var/www/html
      - ./vendor:/var/www/html/vendor
      - ./storage:/var/www/html/storage
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:prvrkVu4bDvOnk7fIcWfKMCgzXI0jAyu5i99osjVpDw=
      DB_CONNECTION: mysql
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_DATABASE: school_management_laravel
      DB_USERNAME: root
      DB_PASSWORD: 25021999
    ports:
      - "8000:80"
    command: >
      sh -c "php artisan config:clear &&
             php artisan route:clear &&
             php artisan view:clear &&
             php artisan serve --host=0.0.0.0 --port=8000"
